### PR TITLE
Gsoc 2023 migrating main activity to compose

### LINKED ISSUE #61: Migrate Main Activity to Compose

### PR DESCRIPTION
**Pull request by narendraanjana09**
Fixes #61 

**Changes :** <br>
Migrated Main Activity to Compose, Added new Top App Bar, Bottom Nav Bar and fixed few bug fixes along it.
<br>**Previous UI:** <br>
image

<br>**New UI ScreenShot**<br>
image

<br>**New UI Screen recording:** <br>
https://drive.google.com/file/d/1cWChlhjyOEiJxzEtVAC4zJVvGf_dCDiW/view?usp=drivesdk

<br>**Appetize App Link**<br>
https://appetize.io/app/d7wqeezvl3ynuojmq2fgpxgow4?device=pixel4&osVersion=11.0&scale=75

### CODE REVIEW

**Comment by hackeramitkumar** [comment]
@narendraanjana09 You have to resolve conflicts..

**Comment by narendraanjana09** [comment]
> @narendraanjana09 You have to resolve conflicts..
resolved.

**Comment by hackeramitkumar** [comment]
@narendraanjana09 rebase it..

**Comment by narendraanjana09** [comment]
> @narendraanjana09 rebase it..

done

**Comment by hackeramitkumar** [comment]
@narendraanjana09 rebase it...

**Comment by narendraanjana09** [comment]
> @narendraanjana09 rebase it...

done

**Comment by hackeramitkumar** [comment]
@narendraanjana09 this is our last pr for the jetpack compose migration. So now you have to fix the linting.

**Comment by hackeramitkumar** [comment]
`gradlew ktlintcheck -p`

Run this command locally and fix the issues.

**Comment by narendraanjana09** [comment]
> `gradlew ktlintcheck -p`
> 
> 
> 
> Run this command locally and fix the issues.

I have tried it before but it seems to me that issue is not here actually out actions ci file is not able to read our secrets thus unable to assign values to variables in build file which leads to non-null error.

**Pull request merged**
