### PR TITLE
Gsoc 2023 migrating create elections fragment to compose

### LINKED ISSUE #28: Migrate Profile Screen to Compose

### LINKED ISSUE #55: Migrate Create Elections Screen to Compose

### PR DESCRIPTION
**Pull request by narendraanjana09**
Fixes #55 

**Changes :** <br>
Migrated Create Election Screen to Jetpack Compose

**Previous UI:** <br>
image

<br>**New UI Screen recording:** <br>

https://github.com/AOSSIE-Org/Agora-Android/assets/60137237/ca7f2b8d-c683-4b99-8fd9-4d74b9da31a9

<br>**Appetize App Link**<br>
https://appetize.io/app/d7wqeezvl3ynuojmq2fgpxgow4?device=pixel4&osVersion=11.0&scale=75

### CODE REVIEW

**Comment by hackeramitkumar** [comment]
@narendraanjana09 rebase it..

**Comment by narendraanjana09** [comment]
> @narendraanjana09 rebase it..

done

**Comment by hackeramitkumar** [comment]
@narendraanjana09 rebase it.

**Comment by narendraanjana09** [comment]
> @narendraanjana09 rebase it.

done

**Comment by hackeramitkumar** [comment]
LGTM

**Review by hackeramitkumar — COMMENTED** [review]
LGTM

**Review by hackeramitkumar — APPROVED** [review]

**Pull request merged**
